import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('file:///C:/Users/franc/Desktop/VendorVibe/index.html');
  await page.getByRole('checkbox', { name: 'Cloud sync A compressed copy' }).check();
  await page.getByRole('checkbox', { name: 'AI Coach When online, only' }).check();
  await page.locator('label').filter({ hasText: 'Alerts when the app is' }).click();
  await page.getByRole('checkbox', { name: 'Alerts when the app is closed' }).check();
  await page.getByRole('checkbox', { name: 'I have read this notice and' }).check();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: '🇬🇧  English' }).click();
  await page.getByRole('button', { name: '🍲 Food & Drinks (carinderia' }).click();
  await page.getByRole('button', { name: 'Just me' }).click();
  await page.getByRole('button', { name: 'Less than 1 year' }).click();
  await page.getByRole('button', { name: '✅ Yes · suggested' }).click();
  await page.getByRole('button', { name: '⛔ No' }).click();
  await page.getByRole('button', { name: '✅ Yes · suggested' }).click();
  await page.getByRole('button', { name: '⛔ No · suggested' }).click();
  await page.getByRole('button', { name: '✅ Yes · suggested' }).click();
  await page.getByRole('button', { name: 'Next →' }).click();
  await page.getByRole('button', { name: 'Continue →' }).click();
  await page.getByRole('button', { name: 'Save Settings' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#tourOv').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#tourHole').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#tourOv').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Done' }).click();
  await page.getByRole('button', { name: '▣ Menu items' }).click();
  await page.getByRole('textbox', { name: 'Search products...' }).click();
  await page.getByRole('textbox', { name: 'Search products...' }).fill('Winter Melon');
  await page.getByRole('button', { name: '＋ Add' }).click();
  await page.getByRole('textbox', { name: 'Menu item name' }).click();
  await page.getByRole('textbox', { name: 'Menu item name' }).fill('Winter Melon');
  await page.getByRole('spinbutton', { name: 'Ingredient cost per item' }).click();
  await page.getByRole('spinbutton', { name: 'Ingredient cost per item' }).fill('15');
  await page.getByRole('spinbutton', { name: 'Selling price' }).click();
  await page.getByRole('spinbutton', { name: 'Selling price' }).fill('30');
  await page.getByRole('spinbutton', { name: 'Low-stock threshold' }).fill('4');
  await page.getByRole('spinbutton', { name: 'Low-stock threshold' }).click();
  await page.getByRole('spinbutton', { name: 'Low-stock threshold' }).fill('5');
  await page.getByRole('spinbutton', { name: 'Low-stock threshold' }).dblclick();
  await page.getByRole('spinbutton', { name: 'Stock', exact: true }).dblclick();
  await page.getByRole('spinbutton', { name: 'Stock', exact: true }).fill('50');
  await page.getByRole('textbox', { name: 'Category' }).click();
  await page.getByRole('textbox', { name: 'Category' }).fill('Drink');
  await page.getByRole('textbox', { name: '⏳ Expiry / best-before date (' }).fill('2026-12-07');
  await page.getByRole('button', { name: 'Save Menu item' }).click();
  await page.getByRole('button', { name: '⋯ More' }).click();
  await page.getByRole('button', { name: '▶ Test alarm' }).click();
  await page.getByRole('button', { name: 'Open now' }).click();
  await page.getByRole('button', { name: 'Restock today' }).click();
  await page.locator('label').filter({ hasText: '1. Stock & Inventory' }).click();
  await page.getByRole('checkbox', { name: '1. Stock & Inventory Check' }).check();
  await page.getByRole('button', { name: '⋯ More' }).click();
  await page.getByRole('button', { name: '⌂ Home' }).click();
  await page.getByRole('button', { name: '⋯ More' }).click();
  await page.getByRole('button', { name: '⋯ More' }).click();
  await page.getByRole('button', { name: '👥 Customers' }).click();
  await page.getByRole('button', { name: '＋ Add' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('Boy ');
  await page.getByRole('button', { name: 'Save Customer' }).click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.getByRole('button', { name: 'Save Customer' }).click();
  await page.getByRole('button', { name: '⋯ More' }).click();
  await page.getByRole('button', { name: '⌂ Home' }).click();
  await page.getByRole('button', { name: '＋ Sale' }).click();
  await page.getByRole('button', { name: 'Save Sale' }).click();
  await page.getByRole('button', { name: '＋ Menu item' }).click();
  await page.getByRole('textbox', { name: 'Menu item name' }).click();
  await page.getByRole('textbox', { name: 'Menu item name' }).fill('Winter Melon');
  await page.getByRole('spinbutton', { name: 'Ingredient cost per item' }).click();
  await page.getByRole('spinbutton', { name: 'Ingredient cost per item' }).fill('15');
  await page.getByRole('spinbutton', { name: 'Selling price' }).click();
  await page.getByRole('spinbutton', { name: 'Selling price' }).fill('30');
  await page.getByRole('spinbutton', { name: 'Stock', exact: true }).dblclick();
  await page.getByRole('spinbutton', { name: 'Stock', exact: true }).fill('50');
  await page.getByRole('spinbutton', { name: 'Low-stock threshold' }).click();
  await page.getByRole('spinbutton', { name: 'Low-stock threshold' }).click();
  await page.getByRole('spinbutton', { name: 'Low-stock threshold' }).fill('5');
  await page.getByRole('textbox', { name: 'Category' }).click();
  await page.getByRole('textbox', { name: 'Category' }).fill('Drink');
  await page.getByRole('textbox', { name: '⏳ Expiry / best-before date (' }).fill('2026-12-07');
  await page.getByRole('button', { name: 'Save Menu item' }).click();
  await page.getByRole('button', { name: 'Talk to Coach' }).click();
  await page.getByRole('textbox', { name: 'Halimbawa: Malaki ang benta' }).click();
  await page.getByRole('textbox', { name: 'Halimbawa: Malaki ang benta' }).fill('Tama lang ba price ko sas winter melon?\n');
  await page.getByRole('textbox', { name: 'Halimbawa: Malaki ang benta' }).click();
  await page.getByRole('textbox', { name: 'Halimbawa: Malaki ang benta' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Halimbawa: Malaki ang benta' }).fill('Tama lang ba price ko sa winter melon?\n');
  await page.getByRole('button', { name: 'Ask Coach' }).click();
  await page.getByRole('textbox', { name: 'Halimbawa: Malaki ang benta' }).click();
  await page.getByRole('textbox', { name: 'Halimbawa: Malaki ang benta' }).fill('May Kita ba ako or competitive ba ang price?\n');
  await page.getByRole('button', { name: 'Ask Coach' }).click();
  await page.getByRole('button', { name: 'Update my business personality' }).click();
  await page.getByRole('button', { name: 'Save Coaching Profile' }).click();
  await page.getByRole('button', { name: '⌂ Home' }).click();
  await expect(page.getByRole('checkbox', { name: '3. Track Utang Balances' })).not.toBeChecked();
  await page.getByRole('checkbox', { name: '5. Reconcile Cash Drawer' }).check();
  await page.getByRole('checkbox', { name: '3. Track Utang Balances' }).check();
  await page.getByRole('checkbox', { name: '2. Record Daily Sales Log' }).check();
  await page.getByRole('checkbox', { name: '4. Log Expenses & Bills' }).check();
  await page.getByRole('checkbox', { name: '6. Review Habit Score Check' }).check();
});