name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci || npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Start local server & run Playwright tests
      run: |
        npx http-server -p 8080 &
        npx playwright test